### ISSUE TITLE
Task: Creating database using Realm in code and defining entities (which are already listed)

### ISSUE THREAD

**Issue by rod-moraes** [rod-moraes/formulize#4]
Description:
This task involves setting up a database using the Realm database management system in code and defining entities for the database. The entities that will be used in the database are already listed and need to be implemented.

### Tasks:
- [x] Add the Realm dependency to the project.
- [x] Define the entities that will be used in the database, based on the specifications provided.
- [x] Implement the entities in the code, making sure to follow best practices for database modeling.
- [x] Create a database instance using the defined entities.
- [x] Test the database by performing CRUD (Create, Read, Update, Delete) operations.
- [x] Acceptance Criteria:

The Realm dependency should be added to the project.
The defined entities should match the specifications provided.
The entities should be implemented in the code according to best practices for database modeling.
The database instance should be created using the defined entities.
The CRUD operations should work correctly in the database.
