### ISSUE TITLE
Task - Form creation (super user) 

### ISSUE THREAD

**Issue by rod-moraes** [rod-moraes/formulize#7]
Description:
The task involves creating a feature to allow a super user to create and manage forms in the system. The forms should be displayed in card format, showing information such as the form name, total number of responses, and status (Enabled or Disabled). The user should also be able to filter the forms by status.

### Tasks:
- [x] Create an interface for creating forms;
- [x] Allow the super user to create and edit forms;
- [x] Display forms in card format;
- [x] Display information such as form name, total number of responses, and status;
- [x] Allow the user to filter the forms by status.

Acceptance criteria:

The code must be well-documented and follow good programming practices;
The super user must be able to create and edit forms;
The forms must be displayed correctly in card format;
The information such as form name, total number of responses, and status must be displayed correctly;
The user must be able to filter the forms by status.
